/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.stu.cipher.view;

import edu.stu.cipher.view.viewModel.CaesarPanel;
import edu.stu.cipher.view.viewModel.VengenerePanel;
import edu.stu.cipher.view.viewModel.PlayfairPanel;
import edu.stu.cipher.view.viewModel.ShiftPanel;

/**
 *
 * @author ngodu
 */
public class ModeSelectionPanel extends javax.swing.JPanel {
    private MainFrame main;
    /**
     * Creates new form ModeSelectionPanel
     */
    public ModeSelectionPanel(MainFrame main) {
        this.main = main;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHome = new javax.swing.JButton();
        btnCaesar = new javax.swing.JButton();
        btnPlayfair = new javax.swing.JButton();
        btnVengenere = new javax.swing.JButton();
        btnShift = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnHome.setBackground(new java.awt.Color(51, 153, 255));
        btnHome.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,255,255), 2, true));
        btnHome.setBorderPainted(false);
        btnHome.setFocusPainted(false);
        btnHome.setVerifyInputWhenFocusTarget(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnCaesar.setBackground(new java.awt.Color(51, 51, 255));
        btnCaesar.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnCaesar.setForeground(new java.awt.Color(255, 255, 255));
        btnCaesar.setText("Ceasar");
        btnCaesar.setBorderPainted(false);
        btnCaesar.setFocusPainted(false);
        btnCaesar.setVerifyInputWhenFocusTarget(false);
        btnCaesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaesarActionPerformed(evt);
            }
        });

        btnPlayfair.setBackground(new java.awt.Color(51, 51, 255));
        btnPlayfair.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnPlayfair.setForeground(new java.awt.Color(255, 255, 255));
        btnPlayfair.setText("Playfair");
        btnPlayfair.setBorderPainted(false);
        btnPlayfair.setFocusPainted(false);
        btnPlayfair.setVerifyInputWhenFocusTarget(false);
        btnPlayfair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayfairActionPerformed(evt);
            }
        });

        btnVengenere.setBackground(new java.awt.Color(51, 51, 255));
        btnVengenere.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnVengenere.setForeground(new java.awt.Color(255, 255, 255));
        btnVengenere.setText("Vengenere");
        btnVengenere.setBorderPainted(false);
        btnVengenere.setFocusPainted(false);
        btnVengenere.setVerifyInputWhenFocusTarget(false);
        btnVengenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVengenereActionPerformed(evt);
            }
        });

        btnShift.setBackground(new java.awt.Color(51, 51, 255));
        btnShift.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnShift.setForeground(new java.awt.Color(255, 255, 255));
        btnShift.setText("Shift");
        btnShift.setBorderPainted(false);
        btnShift.setFocusPainted(false);
        btnShift.setVerifyInputWhenFocusTarget(false);
        btnShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShiftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVengenere, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnCaesar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(123, 123, 123)
                            .addComponent(btnPlayfair, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addComponent(btnShift, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaesar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShift, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnVengenere, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnPlayfair, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        main.showPanel(new StartPanel(main));
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnCaesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaesarActionPerformed
        // TODO add your handling code here:
        main.showPanel(new CaesarPanel(main));
    }//GEN-LAST:event_btnCaesarActionPerformed

    private void btnPlayfairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayfairActionPerformed
        // TODO add your handling code here:
        main.showPanel(new PlayfairPanel(main));
    }//GEN-LAST:event_btnPlayfairActionPerformed

    private void btnVengenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVengenereActionPerformed
        // TODO add your handling code here:
        main.showPanel(new VengenerePanel(main));
    }//GEN-LAST:event_btnVengenereActionPerformed

    private void btnShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShiftActionPerformed
        // TODO add your handling code here:
        main.showPanel(new ShiftPanel(main));
    }//GEN-LAST:event_btnShiftActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaesar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPlayfair;
    private javax.swing.JButton btnShift;
    private javax.swing.JButton btnVengenere;
    // End of variables declaration//GEN-END:variables
}
