/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.stu.cipher.view;

import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author ngodu
 */
public class StartPanel extends javax.swing.JPanel {
    private MainFrame main;
    /**
     * Creates new form StartPanel
     */
    public StartPanel(MainFrame main) {
        this.main = main;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQuit = new javax.swing.JButton();
        btnStart1 = new javax.swing.JButton();
        titleApp = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        btnQuit.setBackground(new java.awt.Color(153, 0, 0));
        btnQuit.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(255, 255, 255));
        btnQuit.setText("QUIT");
        btnQuit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,255,255), 2, true));
        btnQuit.setBorderPainted(false);
        btnQuit.setFocusPainted(false);
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        btnStart1.setBackground(new java.awt.Color(51, 153, 255));
        btnStart1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnStart1.setForeground(new java.awt.Color(255, 255, 255));
        btnStart1.setText("Start");
        btnStart1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,255,255), 2, true));
        btnStart1.setBorderPainted(false);
        btnStart1.setFocusPainted(false);
        btnStart1.setVerifyInputWhenFocusTarget(false);
        btnStart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart1ActionPerformed(evt);
            }
        });

        titleApp.setFont(new java.awt.Font("Old English Text MT", 1, 50)); // NOI18N
        titleApp.setForeground(new java.awt.Color(0, 0, 0));
        titleApp.setText("Cipher Application");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStart1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(278, 278, 278))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleApp)
                        .addGap(191, 191, 191))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(titleApp)
                .addGap(66, 66, 66)
                .addComponent(btnStart1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart1ActionPerformed
        // TODO add your handling code here:
        main.showPanel(new ModeSelectionPanel(main));
    }//GEN-LAST:event_btnStart1ActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnStart1;
    private javax.swing.JLabel titleApp;
    // End of variables declaration//GEN-END:variables
}
